version: "3.9"
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./auth-service:/app
  
  shop-service:
    build:
      context: ./shop-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENV=development
    volumes:
      - ./shop-service:/app
  
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"    # Mapea el puerto interno 8000 del discovery a 8002 en el host (o el puerto que prefieras)
    environment:
      - ENV=development
    volumes:
      - ./discovery-service:/app
