version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--tracing=true"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
      - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
      - "--tracing.jaeger.samplingType=const"
      - "--tracing.jaeger.samplingParam=1.0"
    ports:
      - "80:80"
      - "8082:8080"  # Dashboard UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_dynamic.yml:/etc/traefik/dynamic/traefik_dynamic.yml
    networks:
      - ezto

  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    networks:
      - ezto

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./auth-service:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.middlewares=auth-headers,strip-auth,retry-auth"
      - "traefik.http.middlewares.auth-headers.headers.customrequestheaders.X-From-Traefik=EzTo"
      - "traefik.http.middlewares.retry-auth.retry.attempts=3"
      - "traefik.http.middlewares.retry-auth.retry.initialinterval=500ms"
      - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=/auth"
      - "traefik.http.services.auth.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.auth.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.auth.loadbalancer.healthcheck.timeout=3s"
    networks:
      - ezto
    depends_on:
      - keycloak
      - consul

  promotions-service:
    build:
      context: ./promotions-service
      dockerfile: Dockerfile
    volumes:
    - ./promotions-service:/app

    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.promotions.rule=PathPrefix(`/promotions`)"
      - "traefik.http.routers.promotions.entrypoints=web"
      - "traefik.http.routers.promotions.middlewares=promotions-headers"
      - "traefik.http.middlewares.promotions-headers.headers.customrequestheaders.X-From-Traefik=EzTo"
      - "traefik.http.services.promotions.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.promotions.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.promotions.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.promotions.loadbalancer.server.port=8001"

    networks:
      - ezto
    depends_on:
      - consul

  usermembership-service:
    build:
      context: ./usermembership-service
      dockerfile: Dockerfile
    volumes:
      - ./usermembership-service:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --
    ports:
      - "8002:8002"
    environment:
      - ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.membership.rule=PathPrefix(`/usermemberships`)"
      - "traefik.http.routers.membership.entrypoints=web"
      - "traefik.http.routers.membership.middlewares=membership-headers"
      - "traefik.http.middlewares.membership-headers.headers.customrequestheaders.X-From-Traefik=EzTo"
      - "traefik.http.services.membership.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.membership.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.membership.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.membership.loadbalancer.server.port=8002"

    networks:
      - ezto
    depends_on:
      - consul

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - ezto

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ezto

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - ezto

  nfc-service:
    build:
      context: ./nfc-service
      dockerfile: Dockerfile
    volumes:
      - ./nfc-service:/app
      - ./nfc-service/firebase_credentials.json:/app/firebase_credentials.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    environment:
      - ENV=development
      - SERVICE_ID=nfc-service-1
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nfc.rule=PathPrefix(`/nfc`)"
      - "traefik.http.routers.nfc.entrypoints=web"
      - "traefik.http.routers.nfc.middlewares=nfc-stripprefix,nfc-headers"
      - "traefik.http.middlewares.nfc-stripprefix.stripprefix.prefixes=/nfc"
      - "traefik.http.middlewares.nfc-headers.headers.customrequestheaders.X-From-Traefik=EzTo"
      - "traefik.http.services.nfc.loadbalancer.server.port=8003"
      - "traefik.http.services.nfc.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.nfc.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.nfc.loadbalancer.healthcheck.timeout=3s"

    networks:
      - ezto
    depends_on:
      - consul

volumes:
  pgdata:

networks:
  ezto:
    driver: bridge