http:
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8000"
        healthCheck:
          path: "/health"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

    inventory-service:
      loadBalancer:
        servers:
          - url: "http://inventory-service:8002"
        healthCheck:
          path: "/health"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

    purchase-service:
      loadBalancer:
        servers:
          - url: "http://purchase-service:8004"
        healthCheck:
          path: "/health"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

    shop-service:
      loadBalancer:
        servers:
          - url: "http://shop-service:8001"
        healthCheck:
          path: "/health"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

    supplier-service:
      loadBalancer:
        servers:
          - url: "http://supplier-service:8003"
        healthCheck:
          path: "/health"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

    keycloak:
      loadBalancer:
        servers:
          - url: "http://keycloak:8080"
        healthCheck:
          path: "/"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

    consul:
      loadBalancer:
        servers:
          - url: "http://consul:8500"
        healthCheck:
          path: "/v1/status/leader"
          interval: "5s"
          timeout: "3s"
        passHostHeader: true
        circuitBreaker:
          expression: "NetworkErrorRatio() > 0.5"

  routers:
    auth:
      rule: "PathPrefix(`/auth`)"
      service: "auth-service"
      entryPoints:
        - web
      middlewares:
        - retry-auth

    inventory:
      rule: "PathPrefix(`/inventory`)"
      service: "inventory-service"
      entryPoints:
        - web
      middlewares:
        - retry-auth

    purchase:
      rule: "PathPrefix(`/purchase`)"
      service: "purchase-service"
      entryPoints:
        - web
      middlewares:
        - retry-auth

    shop:
      rule: "PathPrefix(`/shop`)"
      service: "shop-service"
      entryPoints:
        - web
      middlewares:
        - retry-auth

    supplier:
      rule: "PathPrefix(`/supplier`)"
      service: "supplier-service"
      entryPoints:
        - web
      middlewares:
        - retry-auth

    keycloak:
      rule: "PathPrefix(`/keycloak`)"
      service: "keycloak"
      entryPoints:
        - web
      middlewares:
        - retry-auth

    consul:
      rule: "PathPrefix(`/consul`)"
      service: "consul"
      entryPoints:
        - web
      middlewares:
        - retry-auth

  middlewares:
    retry-auth:
      retry:
        attempts: 3
        initialInterval: 500ms
