http:
  middlewares:
    retry-auth:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-promotions:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-usermemberships:
      retry:
        attempts: 3
        initialInterval: 500ms
