http:
  routers:
    config-api:
      rule: "PathPrefix(`/config`)"
      service: config-server
      entryPoints:
        - web
      middlewares:
        - config-strip

    auth:
      rule: "PathPrefix(`/auth`)"
      service: auth-service
      entryPoints:
        - web
      middlewares:
        - strip-auth
        - retry-auth

    inventory:
      rule: "PathPrefix(`/inventory`)"
      service: inventory-service
      entryPoints:
        - web
      middlewares:
        - inventory-strip
        - retry-auth

    purchase:
      rule: "PathPrefix(`/purchase`)"
      service: purchase-service
      entryPoints:
        - web
      middlewares:
        - purchase-strip
        - retry-auth

    shop:
      rule: "PathPrefix(`/shop`)"
      service: shop-service
      entryPoints:
        - web
      middlewares:
        - shop-strip
        - retry-auth

    supplier:
      rule: "PathPrefix(`/supplier`)"
      service: supplier-service
      entryPoints:
        - web
      middlewares:
        - supplier-strip
        - retry-auth

    promotions:
      rule: "PathPrefix(`/promotions`)"
      service: promotions-service
      entryPoints:
        - web
      middlewares:
        - promotions-strip
        - retry-promotions

    usermemberships:
      rule: "PathPrefix(`/usermemberships`)"
      service: usermemberships-service
      entryPoints:
        - web
      middlewares:
        - usermemberships-strip
        - retry-usermembership

    reservations:
      rule: "PathPrefix(`/reservations`)"
      service: reservations-service
      entryPoints:
        - web
      middlewares:
        - reservations-strip
        - retry-reservations

    classes:
      rule: "PathPrefix(`/classes`)"
      service: class-service
      entryPoints:
        - web
      middlewares:
        - classes-strip
        - retry-class

    classes:
      rule: "PathPrefix(`/memberships`)"
      service: memberships-service
      entryPoints:
        - web
      middlewares:
        - retry-memberships

    events:
      rule: "PathPrefix(`/events`)"
      service: event-service
      entryPoints:
        - web
      middlewares:
        - retry-event

    keycloak:
      rule: "PathPrefix(`/keycloak`)"
      service: keycloak
      entryPoints:
        - web
      middlewares:
        - retry-auth

    consul:
      rule: "PathPrefix(`/consul`)"
      service: consul
      entryPoints:
        - web
      middlewares:
        - retry-auth

  services:
    # Se definen en base a etiquetas de los contenedores (no es necesario repetirlos aquí)

  middlewares:
    retry-auth:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-promotions:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-usermembership:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-supplier:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-class:
      retry:
        attempts: 3
        initialInterval: 500ms

    retry-reservations:
      retry:
        attempts: 3
        initialInterval: 500ms

    config-strip:
      stripPrefix:
        prefixes:
          - /config

    strip-auth:
      stripPrefix:
        prefixes:
          - /auth

    shop-strip:
      stripPrefix:
        prefixes:
          - /shop
    inventory-strip:
      stripPrefix:
        prefixes:
          - /inventory
    purchase-strip: 
      stripPrefix:
        prefixes:
          - /purchase
    supplier-strip:
      stripPrefix:
        prefixes:
          - /supplier

    promotions-strip:
      stripPrefix:
        prefixes:
          - /promotions

    usermemberships-strip:
      stripPrefix:
        prefixes:
          - /usermemberships

    reservations-strip:
      stripPrefix:
        prefixes:
          - /reservations

    classes-strip:
      stripPrefix:
        prefixes:
          - /classes
